[package]
name = "aquadoggo_cli"
version = "0.1.0"
authors = [
  "sophiiistika <sophiiistika@mailbox.org>",
  "adz <x12@adz.garden>",
  "sandreae <contact@samandreae.com>",
  "cafca <cafca@001.land>"
]
license = "AGPL-3.0-only"
repository = "https://github.com/p2panda/aquadoggo"
readme = "README.md"
edition = "2018"

[[bin]]
name = "aquadoggo"
path = "src/main.rs"
doc = false

[dependencies]
async-ctrlc = "1.2.0"
async-std = { version = "1.9.0", features = ["unstable", "attributes"] }
env_logger = "0.8.2"
structopt = "0.3.21"

[dependencies.aquadoggo]
version = "~0.1.0"
path = "../aquadoggo"
